### ISSUE TITLE
add `rename` ability

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#105]
This allows rxode ui models to rename parameters, using the `dplyr` s3 method `rename`

**Comment by billdenney** [comment]
The work on this may be tangentially related to #72 and #73.

**Comment by mattfidler** [comment]
Overall yes, though I am unclear about this:

> and in the data? 

My guess is you are talking about the compartment specifications needed in the data itself.  If a compartment is renamed then it corresponding data requirement is also renamed.  Compartment numbers are unlikely to change unless you change a residual to match a compartment.

**Comment by billdenney** [comment]
For the data, I'm not clear that it's a good idea to modify the user's data-- it was mostly for consideration.

The idea of "and the data" would be that if we have a model fit for two PK models and want to then combine them into a multiple PK, single PD model, for instance, we may want to carry the data through the process and modify the compartments as we go.  Or, we may not want to do that because it could be error-prone (and it could possibly include data that the user doesn't intend to include).  Or, we may just want to stay away from automatic data modifications, regardless.

I do think that the user probably would need to use compartment naming rather than numbering for it to work well.

**Comment by mattfidler** [comment]
No only models, no data modification.
