### ISSUE TITLE
Modify rxPkg to not request package upgrades

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#50]
I'm testing it now, and it looks like it's working, but it also appears to be installing some packages on my system (like an updated version of RcppArmadillo, and it is reinstalling rxode2).

_Originally posted by @billdenney in https://github.com/nlmixr2/rxode2/issues/49#issuecomment-1020785005_

**Comment by billdenney** [comment]
I think that the ideal state would be that it would:

* Not install or update by default
* Have an argument to install or update missing/old packages
* If the argument is set not to install/update and the required packages are available but old, issue a warning and continue (the problem with that warning is that it'll get lost in the noise of other messages)
* if the argument is set not to install/update and the required packages are missing, stop with an error
* Otherwise, install/update everything that is needed

**Comment by mattfidler** [comment]
These are mostly devtools calls.  This is not high on my prority list, but could be done at some time.

**Comment by mattfidler** [comment]
For now I will close it. Moving to the new UI, I am unsure how this will be used, if at all.
