### ISSUE TITLE
Add a way to take away boundaries in model piping

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#598]
like `ini(par=fix)` but instead `ini(par=free)`

**Comment by billdenney** [comment]
Can't you do `ini(par =c(-Inf, 1, Inf))`?

**Comment by mattfidler** [comment]
Yes.  But you font keep the estimate.

**Comment by billdenney** [comment]
Ah, taking away the bound while keeping the estimate makes sense as a different thing.

I'd imagine that in the full-featured scenario, you may want to drop the upper bound or the lower bound or both bounds.

My first thought is to use `NA` for the parts that you want to keep, but I don't think that's a good idea because `NA` looks like you would get rid of the value there.

Is it a problem to use the current interface without modification and have it be a bit more effort for the user like this:

```
newEst <- c(-Inf, fixef(model)["par"], Inf)
newModel <- model %>% ini(par = newEst)
```

**Comment by mattfidler** [comment]
close for now
