### ISSUE TITLE
Warn  if `iCov` is specified without sampling times

### ISSUE THREAD

**Issue by tmss1** [nlmixr2/rxode2#599]
For the following simple model with DOSE as a covariate:
```
fm1 <- function() {
  ini({
    CL = 103 # L/h
    V = 7.4 # L
    KAsc_HV = 0.252 # 1/h
    KAsc_18 = 0.233 # 1/h 
    CV = 0.027 # Proportional error 
    SD = 3.15 # Additive error 
  }) 
  model({
    KAsc = KAsc_HV  
    if(DOSE==1.8) KAsc = KAsc_18 
    d/dt(SC) = -KAsc*SC # SC1 amount
    d/dt(CP) = KAsc*SC/V -CL/V*CP # Systemic concentration
    YCP = CP*(1+CV)+SD 
  })
}
mod1 = nlmixr(fm1)
mod1
```

I have this error when trying to input individual covariates with `iCov` that I cannot figure out why: 
![image](https://github.com/nlmixr2/rxode2/assets/32617414/44946af7-6f6e-431e-8cde-30871d794314)

The model works when I input DOSE as a parameter instead:
![image](https://github.com/nlmixr2/rxode2/assets/32617414/c71950d3-2a47-4a79-95c1-fc40df6e7f2e)
![image](https://github.com/nlmixr2/rxode2/assets/32617414/1c618851-2ce9-44ac-8e53-47b01f1e2cd2)

 
 How can I fix this so to simulate with individual covariates?

**Comment by tmss1** [comment]
After much investigation, apparently I need to specify some sampling times for `iCov` to work. Not sure if this is intentional?

**Comment by mattfidler** [comment]
Hi @tmss1 

Thank you for your patience.  I am glad you found the issue.  I believe that I need to probably have a warning for this issue so it will not cause much investigation in the future.
 
> Not sure if this is intentional?

Well, the merge for `iCov` occurs in R before solving, adding missing sampling times occurs within `C`, so it was not considered.  However because of the locations of the two, it will be intentional going forward.  A warning should be sufficient so that people can track down the issue easier.

**Comment by mattfidler** [comment]
I changed the title so I can see what to do for this issue.  Hopefully I will get some time to work on this soon.
