### ISSUE TITLE
Minor documentation issue for rxIndLin_

### ISSUE THREAD

**Issue by billdenney** [nlmixr2/rxode2#85]
The `NULL` here is causing `Warning: [/home/bill/GitHub/rxode2/R/RcppExports.R:1] @title Missing name` while generating the documentation.

I don't know how to remove the NULL.

https://github.com/nlmixr2/rxode2/blob/25872f4c83ba21eea69524a3d878d27a210371fb/R/RcppExports.R#L260-L264

**Comment by mattfidler** [comment]
Nor do I, it only generates a warning though..

**Comment by billdenney** [comment]
@eddelbuettel , There is a minor warning noted above that "@title Missing name" while running `devtools::document()`.  I think that it's related the generation of a NULL above to one of the below two code locations.  I'm not an Rcpp power user, at all.  (I'm an ignorant observer to Rcpp-related processes, overall.)  I think that the warning is generated because of the NULL in the comment above, but I'm not sure why the NULL is generated by `Rcpp::compileAttributes()`; I tried adding `verbose=TRUE`, but that didn't tell me enough to let me know why it's generated that way.

https://github.com/nlmixr2/rxode2/blob/7342f1deb8fb3d68411b9a750870b6f5a217401e/src/expm.cpp#L34-L49

https://github.com/nlmixr2/rxode2/blob/7342f1deb8fb3d68411b9a750870b6f5a217401e/src/expm.cpp#L291-L314

Given the fact that it's a pretty minor issue overall, I don't think that it needs major effort, but if there is a quick and obvious solution, I'd be interested.

**Comment by eddelbuettel** [comment]
Hm, could you be shooting the messenger here?  You appear to be having a `roxygen2` issue which I would think you could fix by adding a line

```c++
//' @title Something Witty Here
```

in `expm.cpp`.  I am not a user of `devtools` as I prefer to see directly what `compileAttributes()` (== an Rcpp function that copies content over to the R file) and `roxygenize()` (which deals with creating docs) do.

**Comment by mattfidler** [comment]
Thank you @eddelbuettel,  

I appreciate the `compileAttributes()` and use it myself since sometimes `devtools` does something I don't expect/like.  I haven't quite used `roxygenize()` yet, but maybe I will find it useful in the future.

We will look at this further.  Thank you for taking your time to answer this request!

**Comment by billdenney** [comment]
Thanks for the review, and I was afraid that I was shooting the messenger.  😄 

I've looked a bit more, and I have something that works to remove the warning (PR coming momentarily).  I wonder if `compileAttributes()` misses the `indLin` C function because of the `extern "C"` in front of the function definition and therefore inserts the `NULL`?  Adding an `//' @name rxIndLin_` in front fixed the warning (and, I think that it causes the correct behavior).

**Comment by eddelbuettel** [comment]
Glad to know!

If you have a few more moments, maybe you can start from `Rcpp.package.skeleton()` and then add a C function or other to try to 'break' this.  It should be pretty robust as approximately ten-year old code by JJ with (literally) millions of uses.   

It should only act on 'tagged' functions with `// [[Rcpp::exports]]` but as it all is regexp based (rather than a full C++ 'parser' which would be devilishly hard) there is always an opening for a new and motivated corner condition.  A test case would help us squash it, if it does indeed exist.

@mattfidler I happen to like doing these things at the command-line in parallel with work from the editor and/or shelled out from the editor so my littler package has scripts `compAttr.r` and `roxy.r` I use for this all day long.  "Works for me".  For `roxy.r` I even optionally cache and older (and, ahem, less "optionated" version) for the basic work of R -> Rd conversion.

**Comment by billdenney** [comment]
Generated as a Rcpp issue.  Hopefully, it's not just PEBKAC.
