### ISSUE TITLE
Add `dose()` and remove `podo()`

### ISSUE THREAD

**Issue by mattfidler** [nlmixr2/rxode2#98]
https://github.com/nlmixrdevelopment/RxODE/issues/314

And add evid for transit-compartment type models

**Comment by billdenney** [comment]
It's not totally clear to me what this addition is.  I think that having the ability to pull all dose-related information information from the last dose makes sense (and, I think that's what this is moving toward).

(I'm not trying to expand the scope of this if it's unrelated.  I am trying to expand the scope of it so that it covers the complete need, if it is related.)

The dose-related columns that I can think of and their closely-related derived values are:

* Dosing compartment
* Time of dose start
* Time since dose start
* Time of dose end (for infusions)
* Time since dose end (for infusions)
* Amount of dose
    * Should we consider something about bioavailability of the dose?
* Rate of infusion
* Duration of infusion
* Is it steady-state dosing?

We would want to account for `II` and `ADDL` within this, too.  It's not clear to me if we would do that by always having the above information relative to the most recent dose if there are `II` and `ADDL` in the data or if there should be an option to choose the time when the dose was initially-specified (i.e. the first of the `II`/`ADDL` doses) and an option to choose the most recent.  (I don't see a lot of value to going back to the initially-specified dose, but I think it's good to consider the option and explicitly reject it rather than not consider it.)

**Comment by mattfidler** [comment]
This is mostly to support transit compartments but...

- Time of dose start -- already available `tlast`, `tlast()`, `tlast(cmt)`
- Time since dose start -- already available `tad`, `tad()`, and `tad(cmt)`
- Time of dose end (for infusions) Not yet available, should be a separate issue
- Time since dose end (for infusions) Not yet available, should be a separate issue
- Amount of dose (this request); will be `dose` `dose()` and `dose(cmt)`

The others are questions:
- Should we consider something about bioavailability of the dose?  Perhaps, but I am unsure how for now
- Rate of infusion
- Duration of infusion
- Is it steady-state dosing?

**Comment by mattfidler** [comment]
Forgot there is also the dose number: `dosenum()`

**Comment by mattfidler** [comment]
For Monolix:

https://mlxtran.lixoft.com/language-reference/dose-related-keywords/
